project:
  type: website
  output-dir: docs
  preview:
    port: 4000
    browser: true
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!files/"    

website:
  title: "HSS8005 {{< iconify line-md plus >}}"
  favicon: "files/img/ncl_coa_hss8005.png"
  navbar:
    pinned: true
    background: "#06074d"
    right:
      - content.qmd
      #- href: index.qmd
      #  text: Home
      - Materials
      - Data
  
  sidebar:
    - title: "Materials"
      style: "floating"
      search: false
      background: none
      contents:
        - section: "Week 1"
          contents:
            - text: "Introduction"
              href: notes/
            - text: "Presentation 1"
              href: slides/
            - text: "Worksheet 1"
              href: worksheets
            - text: "Handout 1"
              href: handouts/
        - section: "Week 2"
          contents:
            - text: "Introduction"
              href: notes/
            - text: "Presentation 1"
              href: slides/
            - text: "Worksheet 1"
              href: worksheets
            - text: "Handout 1"
              href: handouts/
        - section: "Week 3"
          contents:
            - text: "Introduction"
              href: notes/
            - text: "Presentation 1"
              href: slides/
            - text: "Worksheet 1"
              href: worksheets
            - text: "Handout 1"
              href: handouts/
        - section: "Week 4"
          contents:
            - text: "Introduction"
              href: notes/
            - text: "Presentation 1"
              href: slides/
            - text: "Worksheet 1"
              href: worksheets
            - text: "Handout 1"
              href: handouts/
        - section: "Week 5"
          contents:
            - text: "Introduction"
              href: notes/
            - text: "Presentation 1"
              href: slides/
            - text: "Worksheet 1"
              href: worksheets
            - text: "Handout 1"
              href: handouts/
 
    - title: "Data"
      style: "floating"
      search: false
      background: none
      contents:
        - section: "Overview"
          contents:
            - text: "Data 1"
              href: data/

format:
  html:
    theme: 
      - litera
      - html/custom.scss
    toc: true

execute:
  freeze: auto

