project:
  type: website
  output-dir: docs
  preview:
    port: 4000
    browser: true
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!files/"

format:
  html:
    theme: 
      - litera
      - html/custom.scss
    toc: true

# execute:
#   freeze: auto

website:
  title: "HSS8005 {{< iconify line-md plus >}}"
  favicon: "files/img/ncl_coa_hss8005.png"
  search: false
  navbar:
    pinned: true
    background: $ncl-blue
    right:
      - text: "Plan"
        href: plan.qmd
      - text: "Materials"
        href: materials/index.qmd
      - text: "Data"
        href: data/index.qmd
      - text: "{{< iconify arcticons canvasstudent size=l >}} Canvas"
        href: https://canvas.ncl.ac.uk/login/
  
  sidebar:
    - title: "Materials"
      style: "docked"
      search: false
      background: $ncl-blue
      contents:
        - text: " "
          href: materials/index.qmd
        - section: "Week 1"
          href: materials/notes/info_w1.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/notes_w1.qmd
            - text: "Presentation X"
              href: materials/slides/slides_w1.qmd
            - text: "Worksheet X"
              href: materials/worksheets/worksheet_w1.qmd
            - text: "Handout X"
              href: materials/handouts/handout_w1.qmd
        - section: "Week 2"
          href: materials/notes/info_w2.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/week_
            - text: "Presentation X"
              href: materials/slides/week_
            - text: "Worksheet X"
              href: materials/worksheets/week_
            - text: "Handout X"
              href: materials/handouts/week_
        - section: "Week 3"
          href: materials/notes/info_w3.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/week_
            - text: "Presentation X"
              href: materials/slides/week_
            - text: "Worksheet X"
              href: materials/worksheets/week_
            - text: "Handout X"
              href: materials/handouts/week_
        - section: "Week 4"
          href: materials/notes/info_w4.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/week_
            - text: "Presentation X"
              href: materials/slides/week_
            - text: "Worksheet X"
              href: materials/worksheets/week_
            - text: "Handout X"
              href: materials/handouts/week_
        - section: "Week 5"
          href: materials/notes/info_w5.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/week_
            - text: "Presentation X"
              href: materials/slides/week_
            - text: "Worksheet X"
              href: materials/worksheets/week_
            - text: "Handout X"
              href: materials/handouts/week_
        - section: "Week 6"
          href: materials/notes/info_w6.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/week_
            - text: "Presentation X"
              href: materials/slides/week_
            - text: "Worksheet X"
              href: materials/worksheets/week_
            - text: "Handout X"
              href: materials/handouts/week_
        - section: "Week 7"
          href: materials/notes/info_w7.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/week_
            - text: "Presentation X"
              href: materials/slides/week_
            - text: "Worksheet X"
              href: materials/worksheets/week_
            - text: "Handout X"
              href: materials/handouts/week_
        - section: "Week 8"
          href: materials/notes/info_w8.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/week_
            - text: "Presentation X"
              href: materials/slides/week_
            - text: "Worksheet X"
              href: materials/worksheets/week_
            - text: "Handout X"
              href: materials/handouts/week_
        - section: "Week 9"
          href: materials/notes/info_w9.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/week_
            - text: "Presentation X"
              href: materials/slides/week_
            - text: "Worksheet X"
              href: materials/worksheets/week_
            - text: "Handout X"
              href: materials/handouts/week_
        - section: "Week 10"
          href: materials/notes/info_w10.qmd
          contents:
            - text: "Introduction"
              href: materials/notes/week_
            - text: "Presentation X"
              href: materials/slides/week_
            - text: "Worksheet X"
              href: materials/worksheets/week_
            - text: "Handout X"
              href: materials/handouts/week_
    - title: "Data"
      style: "docked"
      search: false
      background: $ncl-blue
      contents:
        - text: "Data dictionaries"
          file: data/index.qmd  
        - text: "Data 1"
          file: data/data1.qmd
        - text: "Data 2"
          file: data/data2.qmd
