project:
  type: website
  output-dir: docs
  preview:
    port: 4000
    browser: true
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!materials/templates/"
format:
  html:
    theme: 
      - litera
      - html/custom.scss
    toc: true
#    toc-location: left
#    citation-location: margin

# execute:
#   freeze: auto

bibliography: hss8005.bib

website:
  title: "HSS8005 {{< iconify line-md plus >}}"
  favicon: "files/img/ncl_coa_hss8005.png"
  search: false
  site-path: "/HSS8005/"
  page-navigation: true
  # reader-mode: true
  
  navbar:
    pinned: true
    background: $ncl-blue
    right:
      - text: "Plan"
        href: plan8.qmd
      - text: "Materials"
        href: materials/index.qmd
      - text: "Data"
        href: data/index.qmd
      - text: "{{< iconify arcticons canvasstudent size=l >}} Canvas"
        href: https://canvas.ncl.ac.uk/login/

metadata-files:
  - _sidebar.yml