project:
  type: website
  output-dir: docs
  preview:
    port: 4000
    browser: true
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!materials/templates/"
    - "!materials/handouts/draft*"
    - "!materials/worksheets/*solved.Rmd"

format:
  html:
    theme: 
      - litera
      - html/custom.scss
    toc: true
#    toc-location: left
#    citation-location: margin

# execute:
#   freeze: auto

#bibliography: hss8005.bib
#suppress-bibliography: true
link-external-newwindow: true
#link-external-icon: true

website:
  title: "HSS8005 {{< iconify line-md plus >}}"
  favicon: "files/img/ncl_coa_hss8005.png"
  search: false
  site-path: "/HSS8005/"
  page-navigation: true
  # page-footer:
  #   border: false
  #  # background: "blue"
  #   center:
  #     - text: "© Chris Moreh, 2023"
  # reader-mode: true
  
  navbar:
    pinned: true
    background: $ncl-blue
    right:
      - text: "Module plan"
        href: plan8.qmd
      - text: "Resources"
        href: resources/index.qmd
      - text: "Materials"
        href: materials/index.qmd
      - text: "Data"
        href: data/index.qmd
      - text: "Assessment"
        href: assessment/index.qmd
      - text: "{{< iconify arcticons canvasstudent size=l >}} Canvas"
        href: https://canvas.ncl.ac.uk/login/

metadata-files:
  - _sidebar.yml