---
title: "Content"
slug: content
summary: "Topic content with links for the HSS8005 module"
toc: false
sidebar: false
page-layout: full
---
          
```{r packages-data, include=FALSE} 
library(tidyverse)
library(knitr)
library(kableExtra)
library(lubridate)
library(glue)
```
   
Here's a guide to the schedule:

<!-- - [**Materials**](/materials/) ({{< fa book-open-reader >}}): This page contains the readings, slides, and recorded lectures (if any) for the topic. Read/watch these first. -->
<!-- - **Tutorial** ({{< fa laptop-code >}}): A link to the tutorial for that week.  -->
<!-- - **Assignment** ({{< fa pen-ruler >}}): This page contains the instructions for each assignment. **Assignments are due by 11:59 PM on the day they're listed.** -->


```{r build-table}
#| echo=FALSE,
#| results="asis" 

# headings <- tribble(
#   ~Week,
#   ~Date,
#   ~Topic,	
#   ~Readings,
#   ~Notes,
#   ~Lecture,
#   ~Slides,
#   ~Worksheets,
#   ~Handouts)
# 
# write_csv(headings, "edit_content.csv")

content <- read_csv("content.csv", show_col_types = FALSE)


# week_count <- content |> count(Week)
# week_index <- week_count |> pull(n) |> set_names(paste0("Week ", week_count$Week))

tbl <- content |>
  # select(-Week) |>
  kbl(escap = FALSE, align = "lllcccccc", table.attr = 'class="schedule-table"') |>
  kable_styling() |>
  column_spec(1, width = "10%") |>  
  column_spec(2, width = "15%") |>  
  column_spec(3, width = "40%") |>  
  column_spec(c(4:6), width = "5%") 
# |>
#   pack_rows(index = week_index,
#               label_row_css = "border-bottom: 2px solid #000000;")

  cat(tbl)


```



  
