---
title: "Module plan"
slug: plan
summary: "Module topic plan with session timetable and link to materials"
toc: false
sidebar: false
page-layout: full
---
          
```{r packages-data, include=FALSE} 
library(tidyverse)
library(knitr)
library(kableExtra)
library(lubridate)
library(glue)
```


```{r build-table, echo=FALSE, results="asis"}

week0 <- as_date("02-02-2023", format = '%d-%m-%Y') - 7

contents <- tibble(
  Week = c(paste("Week", 1:10)),
  TW = c(22:29, 34:35),
  Date = c(week0 + 7*1:8, week0 + 7*13:14),
#  Topic = rep("tbc", 10),
  Topic = c(paste("Topic", 1:10)),
  Info = c(paste0("/materials/notes/info_w", 1:10)),
  Notes = c(paste0("/materials/notes/notes_w", 1:10)),
  Lecture = c(paste0("/materials/slides/slides_w", 1:10)),
  Labs = c(paste0("/materials/worksheets/lab_w", 1:10)),
  Handouts = c(paste0("/materials/handouts/sheet_w", 1:10)),
  )

# write_csv(contents, "files/contents.csv") 

contents <- contents |>
  mutate(Date = format(as_date(Date), "%d %B"),
         Info = paste0("[{{< fa solid circle-info >}}]", glue('({Info}.qmd)')),
         Notes = paste0("[{{< fa solid book-open >}}]", glue('({Notes}.qmd)')),
         Lecture = paste0("[{{< fa solid person-chalkboard >}}]", glue('({Lecture}.qmd)')),
         Labs = paste0("[{{< fa solid laptop-code >}}]", glue('({Labs}.qmd)')),
         Handouts = paste0("[{{< fa solid sheet-plastic >}}]", glue('({Handouts}.qmd)')),
         Topic = recode(Topic, 
                        "Topic 1" = "Introduction", 
                        "Topic 2" = "Review of linear models",
                        "Topic 3" = "Something else"))

tbl <- contents |>
  kbl(escap = FALSE, align = "llllccccc", table.attr = 'class="schedule-table"') |>
  kable_styling() |>
  column_spec(1, width = "8%") |>  
  column_spec(2, width = "5%") |>  
  column_spec(3, width = "10%") |>  
  column_spec(4, width = "45%") |>  
  column_spec(c(5:9), width = "5%") 

  cat(tbl)

```

