

### Prerequisites

To benefit the most from this module, students are expected to have a foundational level of knowledge in quantitative methods: a good understanding of data types and distributions, familiarity with inferential statistics, and some exposure to linear regression. 

Those who don't feel completely up to date with linear regression but are determined to advance more quickly and read/practice beyond the compulsory material during weeks 1-3 are also encouraged to sign up.

Those with a stronger background in multiple linear regression (e.g. students with undergraduate-level training in econometrics) will still benefit from weeks 1-3 as the approach we are taking is probably different from the one they are familiar with.

The module has a strong focus on practical data analysis using the open-source {{< fa brands r-project size="1x">}} statistical programming language (with a focus on the {{< iconify simple-icons tidyverse size="1x">}}`{tidyverse}` dialect). **No previous knowledge of {{< fa brands r-project size="1x">}} or command-based statistical analysis software is needed.** Gaining basic experience with using {{< fa brands r-project size="1x">}} via the <iconify-icon inline icon="file-icons:rstudio" style="color: #7dbefc;"></iconify-icon>**Studio** API is part of the skills development aims of the module. 
But this is not a general data science module, and the IT labs will cover a very limited number of functions (from both base `R`, the `tidyverse` and other reliable user-written [packages](https://cran.r-project.org/web/packages/)) that are most useful for tackling specific analysis tasks. Students are advised to complete some additional self-paced free online training in the use of the software, such as Data Carpentry’s [**R for Social Scientists**](https://datacarpentry.org/r-socialsci/), and to consult Wickham, Çetinkaya-Rundel and Grolemund's [**R for Data Science** (2nd ed.)](https://r4ds.hadley.nz/) online book.