---
title: ""
page-layout: full
---


::: panel-tabset

## Readings

{{< include _readings.qmd >}}

## Software

{{< include _software.qmd >}}

## Training

{{< include _training.qmd >}}

## Help

There are several ways to get help with `R` outside class. If you encounter an error message or are looking for a function to perform a specific task that we have not covered in class, you can do a Google search; for best results, use the [https://rseek.org/](https://rseek.org/) search engine, which limits the results to those relating to the `R` language.

You can also search for answers on [Stack Overflow](https://stackoverflow.com/questions/tagged/r), which is a popular help and discussion website for programmers. You can also post a question there, but make sure to follow community standards and advice on [how to ask a good question](https://stackoverflow.com/help/how-to-ask) and how to [provide a minimal reproducible example](https://stackoverflow.com/a/5963610/16962987). You will need some experience using the site before being able to ask a good question, but it's more than certain that any quesiton you have at this stage will have an answer already somewhere.

## Other

Any further study resources will be listed here.

:::
