---
title: "Data documentation"
page-layout: full
toc: false
sidebar: false
execute:
  echo: false
bibliography: ../hss8005.bib
css: ../html/nobiblio.css
---

Datasets used throughout the course will be available for download from this page soon.


```{r}
#| eval: false
#| include: false
# Table contents

library("tibble")
library("kableExtra")
# library("reactable") # maybe add searchability to the table

content <- tribble(
  ~"File name", ~"Type", ~"Description", ~"Link to source",
  # datasets
  
  ## evs2017
  paste("[evs2017](https://cgmoreh.github.io/HSS8005-24/data/evs2017.rds)"), 
  ".Rds",
  "European Values Study; Wave 5 (2017-2021)",
  paste("[Source](https://search.gesis.org/research_data/ZA7500)"),
  # add <br> and more link lines where available
  
  ## wvs56
  paste("[wvs56](https://cgmoreh.github.io/HSS8005-24/data/wvs56.rds)"), ".Rds",
      "Worlds Values Survey; combined Wave 5 and 6",
      paste("[Source](https://www.worldvaluessurvey.org/wvs.jsp)"),
  
  ## osterman
  paste("[osterman](https://cgmoreh.github.io/HSS8005-data/osterman.dta)"), ".dta",
      "Replication data for @Osterman2021CanWeTrustEducationFostering, based on European Social Survey Rounds 1-9 data",
      paste("[Data source](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/RCSCDA)", "<br>", "[Open access article](https://link.springer.com/article/10.1007/s11205-020-02529-y)", "<br>", "[Supplementary materials](https://static-content.springer.com/esm/art%3A10.1007%2Fs11205-020-02529-y/MediaObjects/11205_2020_2529_MOESM1_ESM.pdf)"),
  
  ## LaddLenz
  paste("[LaddLenz](https://cgmoreh.github.io/HSS8005-data/LaddLenz.dta)"), ".dta",
      "Replication data for @LaddLenz2009ExploitingRareCommunicationShiftDocument, based on British Election Panel Study data. Included in @Hainmueller2012EntropyBalancingCausalEffectsMultivariate",
      paste("[Source](https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/16077)"),
  
  ## EverydayTrust
  paste("[EverydayTrust](https://cgmoreh.github.io/HSS8005-data/EverydayTrust.Rds)"), ".Rds", 
      "Replication data for @WeissEtAl2021TrustEverydayLife", 
      paste("[Source](https://osf.io/kwp6n/)"),

  ## Valentino
  paste("[Valentino17](https://cgmoreh.github.io/HSS8005/data/Valentino17.dta)"), ".dta", "Replication data for @ValentinoEtAl2019EconomicCulturalDriversImmigrantSupport, based on original data collected through YouGov in 11 countries. The original dataset provided by the authors is called ***imm.bjpols.dta*** and the original analysis was performed in Stata.",
      paste("[Data source](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/R5MEKK)", "<br>", "[Open access article](https://ora.ox.ac.uk/objects/uuid:33db61d3-a72c-4dc1-8ad5-53fc37728650)", "<br>", "[Supplementary materials](https://static.cambridge.org/content/id/urn:cambridge.org:id:article:S000712341700031X/resource/name/S000712341700031Xsup001.pdf)"),
  
  ## Ejrnæs
  paste("[Ejrnaes21](https://cgmoreh.github.io/HSS8005/data/Ejrnaes21.dta)"), 
  ".dta", 
  "Replication data for @EjrnaesJensen2021GoYourOwnWayPathways, based on data from the European Social Survey Round 8. The original dataset provided by the authors is called ***G&O_Final.tab*** and the original analysis was performed in Stata.",
  paste("[Data source](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VAFIIO)", 
        "<br>", 
        "[Open access article](https://research.cbs.dk/en/publications/go-your-own-way-the-pathways-to-exiting-the-european-union)", 
        "<br>", 
        "[Supplementary materials](https://static.cambridge.org/content/id/urn:cambridge.org:id:article:S0017257X20000378/resource/name/S0017257X20000378sup001.docx)"
        ),
  
  ## workout
  paste("[workout](https://cgmoreh.github.io/HSS8005/data/workout.Rds)"), 
  ".Rds", 
  "Example dataset from @MehmetogluMittner2021AppliedStatisticsUsingGuideSocial; a combined version of the original `workout2` and `workout3` datasets included in the {astatur} package",
  paste("[Data source](https://github.com/ihrke/astatur/tree/master/data)"),
  
  ## galtonpeas
  paste("[galtonpeas](https://cgmoreh.github.io/HSS8005-data/galtonpeas.Rds)"), ".Rds",
      "Data underpinning a paper presented by Sir Francis Galton to the Royal Institute on February 9, 1877, summarising his experiments on sweet peas in which he compared the size of peas produced by parent plants to those produced by offspring plants.",
      paste("[Source](https://rdrr.io/rforge/alr4/man/galtonpeas.html)"),
  
  ## galton1886
  paste("[galton1886](https://cgmoreh.github.io/HSS8005-data/galton1886.dta)"), ".dta",
      "Sir Francis Galton's famous data on the heights or parents and their children underpinning his 1886 paper [@Galton1886RegressionMediocrityHereditaryStature].",
      paste("[Source and more info](http://www.medicine.mcgill.ca/epidemiology/hanley/galton/)"),
  
  ## Berkeley1973
  paste("[berkeley](https://cgmoreh.github.io/HSS8005-24/data/berkeley.csv)"),
  ".csv",
  "Data underpinning the classic *Sex Bias in Graduate Admissions: Data from Berkeley* paper by Bickel, Hammel and O'Connell (1975).",
  paste("[Data source](https://discovery.cs.illinois.edu/dataset/berkeley/)",
        "<br>",
        "[Original article](https://www.science.org/doi/10.1126/science.187.4175.398)"
        )
)


content2 <- content |> 
  kbl(escap = FALSE) |> 
  kable_styling(bootstrap_options = c("condensed","hover"),
                font_size = 14) |>
  column_spec(1, width = "10%", extra_css = "vertical-align:top;") |>  
  column_spec(2, width = "5%", extra_css = "vertical-align:top;") |>  
  column_spec(3, width = "70%", extra_css = "vertical-align:top;")

```

::: text-sm
```{r results="asis"}
#| eval: false
#| include: false
cat(content2)
```
:::

<!-- The datasets can be downloaded by clicking on the file name, or read into `R` directly from `"https://cgmoreh.github.io/HSS8005-24/data/___"` (using a type-appropriate read function and replacing \_\_\_ with "File name" and "Type" extension; e.g. `sjlabelled::read_stata("https://cgmoreh.github.io/HSS8005-24/data/dataset.dta")` or `datawizard::data_read("https://cgmoreh.github.io/HSS8005-24/data/dataset.dta")`). -->

