---
title: "Week 1 Computer Lab Worksheet"
author: "{{< var author >}}"
date: "{{< var date.w1 >}}"

abstract: ""
abstract-title: "Description"
---

{{< var date.w1 >}}


# Lab 1 

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.


```{r, filename="How to use `kable`"}
knitr::kable(
  mtcars[1:3, 1:3]
)
```


## Heading 2

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.


# ff

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

# gg

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

## gg

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.


# g

# l

# u 
