---
title: "Data documentation"
page-layout: full
toc: false
sidebar: false
execute:
  echo: false
bibliography: ../hss8005.bib
css: ../html/nobiblio.css
---

The datasets listed in the table below can be read into `R` from `"https://cgmoreh.github.io/HSS8005-data/___"` (using a type-appropriate read function and replacing \_\_\_ with "File name" and "Type" extension; e.g. `dataset <- haven::read_dta("https://cgmoreh.github.io/HSS8005-data/dataset.dta")`).

```{r}
# Table contents

library("tibble")
library("kableExtra")
# library("reactable") # maybe add searchability to the table

content <- tribble(
  ~"File name", ~"Type", ~"Description", ~"Link to source",
  # datasets
  ## evs5
  paste("[evs5](https://cgmoreh.github.io/HSS8005-data/evs5.sav)"), ".sav",
      "European Values Study; Wave 5 (2017-2021)",
      paste("[Source](https://search.gesis.org/research_data/ZA7500)"),# add <br> and more link lines where available
  ## osterman
  paste("[osterman](https://cgmoreh.github.io/HSS8005-data/osterman.dta)"), ".dta",
      "Replication data for @Osterman2021CanWeTrustEducationFostering, based on European Social Survey Rounds 1-9 data",
      paste("[Source](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/RCSCDA)" ),
  ## LaddLenz
  paste("[LaddLenz](https://cgmoreh.github.io/HSS8005-data/LaddLenz.dta)"), ".dta",
      "Replication data for @LaddLenz2009ExploitingRareCommunicationShiftDocument, based on British Election Panel Study data. Included in @Hainmueller2012EntropyBalancingCausalEffectsMultivariate",
      paste("[Source](https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/16077)"),
  ## EverydayTrust
  paste("[EverydayTrust](https://cgmoreh.github.io/HSS8005-data/EverydayTrust.Rds)"), ".Rds", 
      "Replication data for @WeissEtAl2021TrustEverydayLife", 
      paste("[Source](https://osf.io/kwp6n/)"),
  ## galtonpeas
  paste("[galtonpeas](https://cgmoreh.github.io/HSS8005-data/galtonpeas.Rds)"), ".Rds",
      "Data underpinning a paper presented by Sir Francis Galton to the Royal Institute on February 9, 1877, summarising his experiments on sweet peas in which he compared the size of peas produced by parent plants to those produced by offspring plants.",
      paste("[Source](https://rdrr.io/rforge/alr4/man/galtonpeas.html)"),
  ## galton1886
  paste("[galton1886](https://cgmoreh.github.io/HSS8005-data/galton1886.dta)"), ".dta",
      "Sir Francis Galton's famous data on the heights or parents and their children underpinning his 1886 paper [@Galton1886RegressionMediocrityHereditaryStature].",
      paste("[Source and more info](http://www.medicine.mcgill.ca/epidemiology/hanley/galton/)")
)

content2 <- content |> 
  kbl(escap = FALSE) |> 
  kable_styling(bootstrap_options = c("condensed","hover"),
                font_size = 14) |>
  column_spec(1, width = "10%", extra_css = "vertical-align:top;") |>  
  column_spec(2, width = "5%", extra_css = "vertical-align:top;") |>  
  column_spec(3, width = "70%", extra_css = "vertical-align:top;")

```

::: text-sm
```{r results="asis"}
cat(content2)
```
:::
