---
title: "1. Introduction to probability"
author: "{{< var author >}}"
format:
  html: default
#  pdf: default
bibliography: ../../hss8005.bib
page-layout: full
toc-location: left
---


nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

## Heading 2

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n. [@abadía-barrero2019]

# ff

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n. [@abadía-barrero2019]

# gg

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

## gg

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

# g

# l



