---
title: "1. Introduction to probability"
author: "{{< var author >}}"
format:
  html: default
#  pdf: default
categories: ""

---

```{r eval=FALSE}

sidebar <- readLines("../../_sidebar.yml")

readLines("../../_sidebar.yml") |>
  stringr::str_replace(
    pattern = "#href: materials/slides/slides_w1.qmd", 
    replace = "href: materials/slides/slides_w1.qmd") |> 
  writeLines(con = "../../_sidebar.yml")
```


nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

## Heading 2

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n. [@abadía-barrero2019]

# ff

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n. [@abadía-barrero2019]

# gg

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

## gg

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk kjn msj nkxc jhbakn xn adjk badfjk vjkx jhdfbvjkn sdkibvkja adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

# g

# l



