---
title: "Week 1 Computer Lab Worksheet"
author: "{{< var author >}}"
format:
  html: default
bibliography: ../../hss8005.bib
---




# Heading 1

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.


## Heading 2

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.


# ff

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

# gg

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.

## gg

nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.nadvjo lafnbodn vn iohjfoiasdh vunfuivnsuion zj nuinvodn do n on ojcn ijfb j c bdu nk ijd jk  kjn msj nkxc jhbakn xn adjk  badfjk vjkx jhdfbvjkn sdkibvkja  adasdvsv. vjklnadfl; njklscv.adjksvpbaui nd n.


# g

# l

# u 
